### PR TITLE
not working. this line is making node to crash

### PR DESCRIPTION
**Pull request by martyalicante**
error: [meta/css] Could not minify LESS/CSS: .fix-lists is undefined

class is not present on any tpl so i just deleted it

### CODE REVIEW

**Comment by julianlam** [comment]
It is present in the latest version of NodeBB core, so please make sure you are up to date.

**Comment by martyalicante** [comment]
I use 0.7.x and up to date :/

**Comment by julianlam** [comment]
What version of the vanilla theme?

**Comment by martyalicante** [comment]
Last one. 3.0.1 Updated it from admin panel.

**Comment by julianlam** [comment]
That would be why. Please stick to the v2.x versions for NodeBB v0.7.x.

**Comment by martyalicante** [comment]
Thank you. Just cloned 0.7 branch and Node ask me for 3.0.1 ir order to use vanilla. With 2.0.x it ask for node upgrade
Also compatibility is set to 0.7.1 on last package so its a bit messy

**Comment by julianlam** [comment]
It asked you?

NodeBB on v0.7.x branch *specifically installs v2.x*:
https://github.com/NodeBB/NodeBB/blob/v0.7.x/package.json#L53

It *does* say you can upgrade Vanilla, but that should be ignored...

**Pull request closed without merging**
